package dataLayer;

import java.sql.*;
import java.util.ArrayList;
import java.util.function.Function;

/**
 * Helper class for Sql query execution on a database
 */
public class SqlHelper {
    private final String connectionString;

    public SqlHelper(String connectionString) {
        this.connectionString = connectionString;
    }

    /**
     * Get first entity returned by Sql query.
     * @param sqlText Sql query text.
     * @param mapper Mapper from ResultSet to the entity type.
     * @param <T> Type of the entity.
     * @return First entity returned by the query, or null, if query returned empty set
     */
    public <T> T getEntity(String sqlText, Function<ResultSet, T> mapper) {
        return getEntity(sqlText, null, mapper);
    }

    /**
     * Get first entity returned by Sql query with single parameter.
     * @param sqlText Sql query text.
     * @param parameter Parameter for query text.
     * @param mapper Mapper from ResultSet to the entity type.
     * @param <T> Type of the entity.
     * @return First entity returned by the query, or null, if query returned empty set
     */
    public <T> T getEntity(String sqlText, Object parameter, Function<ResultSet, T> mapper) {
        return getEntity(sqlText, new Object[]{parameter}, mapper);
    }

    /**
     * Get first entity returned by Sql query with multiple parameters.
     * @param sqlText Sql query text.
     * @param parameters Array of parameters for query text.
     * @param mapper Mapper from ResultSet to the entity type.
     * @param <T> Type of the entity.
     * @return First entity returned by the query, or null, if query returned empty set
     */
    public <T> T getEntity(String sqlText, Object[] parameters, Function<ResultSet, T> mapper) {
        var list = getEntityList(sqlText, parameters, mapper);
        return (list == null || list.size() == 0) ? null : list.get(0);
    }

    /**
     * Get entity list returned by Sql query.
     * @param sqlText Sql query text.
     * @param mapper Mapper from ResultSet to the entity type.
     * @param <T> Type of the entity.
     * @return Entity list returned by the query.
     */
    public <T> ArrayList<T> getEntityList(String sqlText, Function<ResultSet, T> mapper) {
        return getEntityList(sqlText, null, mapper);
    }

    /**
     * Get entity list returned by Sql query with single parameter.
     * @param sqlText Sql query text.
     * @param parameter Parameter for query text.
     * @param mapper Mapper from ResultSet to the entity type.
     * @param <T> Type of the entity.
     * @return Entity list returned by the query.
     */
    public <T> ArrayList<T> getEntityList(String sqlText, Object parameter, Function<ResultSet, T> mapper) {
        return getEntityList(sqlText, new Object[]{parameter}, mapper);
    }

    /**
     * Get entity list returned by Sql query with multiple parameters.
     * @param sqlText Sql query text.
     * @param parameters Array of parameters for query text.
     * @param mapper Mapper from ResultSet to the entity type.
     * @param <T> Type of the entity.
     * @return Entity list returned by the query.
     */
    public <T> ArrayList<T> getEntityList(String sqlText, Object[] parameters, Function<ResultSet, T> mapper) {
        try (var connection = DriverManager.getConnection(connectionString)) {
            var statement = connection.prepareStatement(sqlText);
            initPreparedStatement(statement, parameters);

            ResultSet set = statement.executeQuery();
            var result = new ArrayList<T>();
            while (set.next()) {
                result.add(mapper.apply(set));
            }
            return result;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Checks if Sql query returns non-empty set.
     * @param sqlText Sql query text.
     * @param parameters Array of parameters for query text.
     * @return true if query returned non-empty set, false otherwise.
     */
    public boolean rowExists(String sqlText, Object[] parameters) {
        try (var connection = DriverManager.getConnection(connectionString)) {
            var statement = connection.prepareStatement(sqlText);
            initPreparedStatement(statement, parameters);

            ResultSet rs = statement.executeQuery();

            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Executes query on database inside single transaction.
     * @param sqlText Sql query text.
     * @return If a key was generated by the query (e.g., new id generated by insert query), returns the generated key; otherwise returns 0
     */
    public int execSql(String sqlText) {
        return execSql(sqlText, null);
    }

    /**
     * Executes query on database inside single transaction.
     * @param sqlText Sql query text.
     * @param parameters Array of parameters for query text.
     * @return If a key was generated by the query (e.g., new id generated by insert query), returns the generated key; otherwise returns 0
     */
    public int execSql(String sqlText, Object[] parameters) {
        Connection connection = null;
        try {
            connection = DriverManager.getConnection(connectionString);
            connection.setAutoCommit(false);
            var statement = connection.prepareStatement(sqlText, PreparedStatement.RETURN_GENERATED_KEYS);
            initPreparedStatement(statement, parameters);

            statement.executeUpdate();

            int newId = 0;
            var resultSet = statement.getGeneratedKeys();
            if (resultSet.next()) {
                newId = resultSet.getInt(1);
            }

            connection.commit();

            return newId;
        } catch (SQLException e) {
            if (connection != null) {
                try {
                    connection.rollback();
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
            }
            e.printStackTrace();
            return 0;
        }
    }

    private void initPreparedStatement(PreparedStatement statement, Object[] parameters) throws SQLException {
        if (parameters != null) {
            for (int idx = 0; idx < parameters.length; idx++) {
                statement.setObject(idx + 1, parameters[idx]);
            }
        }
    }
}
